// Builds the browser side into ./public:  app.<hash>.js, styles.<hash>.css,
// index.html (pointing at them), sw.js and the static files.
//
//   node build.mjs            development build (readable, source maps)
//   node build.mjs --prod     minified production build
//   node build.mjs --watch    rebuild when a client file changes
//
// VITE_API_URL / VITE_WS_URL (optional) point the browser at a server on
// another origin; left empty, the page talks to the server it came from.

import esbuild from 'esbuild';
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { fileURLToPath } from 'node:url';

const ROOT = path.dirname(fileURLToPath(import.meta.url));
const OUT = path.join(ROOT, 'public');
const prod = process.argv.includes('--prod') || process.env.NODE_ENV === 'production';
const watch = process.argv.includes('--watch');

const hash = (data) => crypto.createHash('sha1').update(data).digest('hex').slice(0, 10);

async function build() {
  fs.mkdirSync(OUT, { recursive: true });
  for (const f of fs.readdirSync(OUT)) if (/^(app|styles)\.[0-9a-f]{10}\.(js|css|js\.map)$/.test(f) || f === 'sw.js') fs.rmSync(path.join(OUT, f));

  // the program
  const js = await esbuild.build({
    entryPoints: [path.join(ROOT, 'client/main.ts')],
    bundle: true, format: 'esm', target: 'es2020', minify: prod, sourcemap: prod ? false : 'external',
    write: false, outdir: OUT, logLevel: 'warning',
    define: { __API_URL__: JSON.stringify(process.env.VITE_API_URL || ''), __WS_URL__: JSON.stringify(process.env.VITE_WS_URL || '') },
  });
  const code = js.outputFiles.find((f) => f.path.endsWith('.js'));
  const map = js.outputFiles.find((f) => f.path.endsWith('.map'));
  const jsName = `app.${hash(code.contents)}.js`;
  fs.writeFileSync(path.join(OUT, jsName), prod ? code.text : code.text.replace(/\/\/# sourceMappingURL=.*$/m, `//# sourceMappingURL=${jsName}.map`));
  if (map) fs.writeFileSync(path.join(OUT, `${jsName}.map`), map.text);

  // the look
  const css = await esbuild.transform(fs.readFileSync(path.join(ROOT, 'client/styles.css'), 'utf8'), { loader: 'css', minify: prod });
  const cssName = `styles.${hash(css.code)}.css`;
  fs.writeFileSync(path.join(OUT, cssName), css.code);

  // the page
  const html = fs.readFileSync(path.join(ROOT, 'client/index.html'), 'utf8').replace('__CSS__', cssName).replace('__JS__', jsName);
  fs.writeFileSync(path.join(OUT, 'index.html'), html);

  // static files
  const statics = fs.existsSync(path.join(ROOT, 'client/static')) ? fs.readdirSync(path.join(ROOT, 'client/static')) : [];
  for (const f of statics) fs.copyFileSync(path.join(ROOT, 'client/static', f), path.join(OUT, f));

  // The service worker keeps only the app's own files, so it opens fast and works as an installed app.
  // It never touches /api or /health: a game's live state is never cached.
  const assets = ['/', '/index.html', `/${jsName}`, `/${cssName}`, ...statics.filter((f) => !f.startsWith('sw')).map((f) => `/${f}`)];
  const version = hash(assets.join('|') + code.text.length);
  fs.writeFileSync(path.join(OUT, 'sw.js'), `// generated by build.mjs
const CACHE = 'duel-${version}';
const ASSETS = ${JSON.stringify(assets)};
self.addEventListener('install', (e) => { e.waitUntil(caches.open(CACHE).then((c) => c.addAll(ASSETS)).then(() => self.skipWaiting())); });
self.addEventListener('activate', (e) => { e.waitUntil(caches.keys().then((ks) => Promise.all(ks.filter((k) => k !== CACHE).map((k) => caches.delete(k)))).then(() => self.clients.claim())); });
self.addEventListener('fetch', (e) => {
  const u = new URL(e.request.url);
  if (e.request.method !== 'GET' || u.origin !== location.origin || u.pathname.startsWith('/api') || u.pathname === '/health') return;
  if (e.request.mode === 'navigate') { e.respondWith(fetch(e.request).catch(() => caches.match('/index.html'))); return; }
  e.respondWith(caches.match(e.request).then((hit) => hit || fetch(e.request)));
});
`);
  console.log(`built ${jsName} (${Math.round(code.contents.length / 1024)} KB)${prod ? ' [production]' : ''}`);
}

await build();
if (watch) {
  let t = null;
  for (const dir of ['client', 'shared']) {
    fs.watch(path.join(ROOT, dir), { recursive: true }, () => { clearTimeout(t); t = setTimeout(() => build().catch((e) => console.error(e.message)), 120); });
  }
  console.log('watching client/ and shared/ ...');
}
